spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/rollcall0?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
    username: root
    password: root
    #db1:
      #driver-class-name: com.mysql.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost:3306/rollcall0?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      #username: root
      #password: root
    #db2:
      #driver-class-name: com.mysql.jdbc.Driver
      #jdbc-url: jdbc:mysql://localhost:3306/rollcall1?serverTimezone=UTC&serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=UTF-8
      #username: root
      #password: root
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
  #activemq:
    #user: admin
    #password: admin
    #broker-url: tcp://127.0.0.1:61616
  #jms:
    #topic-name: topic
    #queue-name: queue
  data:
    elasticsearch:
      repositories:
        enabled: true
      cluster-nodes: 127.0.0.1:9300
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  config-location: classpath:mybatis-config.xml